- id: update
  name: git add
  description: Adds changes to the git index
  entry: pre-commit-git-add
  args: ["--update"]
  pass_filenames: false
  language: python
  require_serial: true
  fail_fast: true
